### PR TITLE
Upgrade to CodeMirror 5

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**
I upgraded the current extra to use the latest CodeMirror.
One thing i am currently working on is the search function which i will add in a commit soon.
As to the changes concerning the codemirror Files i was thinking of removing the uncompressed codemirror files.
Also i currently use a cdn for the codemirror File but i think i will switch these to local files.

I would appreciate you feedback as this is my first deeper dive into extra developement.

### CODE REVIEW

**Comment by WebsiteDeveloper** [comment]
I am also thinking about working on the other issues reported.

**Comment by WebsiteDeveloper** [comment]
@jpdevries

**Comment by jpdevries** [comment]
Thanks @WebsiteDeveloper. I'll take a look soon. As far as the CDN, Ideally it would be nice if there is an option whether or not to use a CDN, and if a CDN is used still load a local fallback (incase the CDN is unreachable)

**Comment by WebsiteDeveloper** [comment]
Yeah i think that would be a good idea will probably add this tomorrow when i have a bit of time

**Comment by jpdevries** [comment]
Sounds good @WebsiteDeveloper. I'll wait a few days before merging it to give you some time then ;)

**Comment by WebsiteDeveloper** [comment]
Gonna work on it sometime this evening

**Comment by jpdevries** [comment]
Hey @WebsiteDeveloper just checking in on this. Do you think the PR is ready to be merged as is? Or since it has been a while, any further updates needed?

**Comment by WebsiteDeveloper** [comment]
Oh i totally forgot about this pull 
I will check if any updates are necessary and push them the next few days if i have the time :)

**Comment by jpdevries** [comment]
@WebsiteDeveloper No worries! I totally forgot we "maintained" it until @Mark-H asked me about it 🙃

**Pull request closed without merging**
